version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    networks:
      - devnet
    volumes:
      - psqldata_gear:/var/lib/postgresql/data
      - ./scripts/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql:ro
      - ./scripts/postgres_always.sh:/postgres_always.sh:ro
      - ./scripts/postgres_run.sh:/usr/local/bin/postgres_run.sh:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "psql -U fence_user -d fence_db -c 'SELECT 1;'"]
      interval: 60s
      timeout: 5s
      retries: 3
    command: postgres_run.sh
    environment:
      - POSTGRES_PASSWORD=postgres
  fence-service:
    image: "quay.io/pcdc/fence:2021.08"
    command: bash /var/www/fence/fence_setup.sh
    container_name: fence-service
    networks:
      - devnet
    volumes:
      - ./Secrets/fence-config.yaml:/var/www/fence/fence-config.yaml
      - ./Secrets/user.yaml:/var/www/fence/user.yaml
      - ./Secrets/TLS/service.crt:/usr/local/share/ca-certificates/cdis-ca.crt
      - ./Secrets/fenceJwtKeys:/fence/keys
      - ./scripts/fence_setup.sh:/var/www/fence/fence_setup.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/_status"]
      interval: 60s
      timeout: 5s
      retries: 3
    environment:
      - PYTHONPATH=/var/www/fence
      - GEN3_DEBUG=True
    depends_on:
      - postgres
      - arborist-service
  arborist-service:
    image: "quay.io/cdis/arborist:2021.08"
    container_name: arborist-service
    entrypoint: bash /go/src/github.com/uc-cdis/arborist/arborist_setup.sh
    networks:
      - devnet
    volumes:
      - ./scripts/arborist_setup.sh:/go/src/github.com/uc-cdis/arborist/arborist_setup.sh
    environment:
      - JWKS_ENDPOINT=http://fence-service/.well-known/jwks
      - PGDATABASE=arborist_db
      - PGUSER=arborist_user
      - PGPASSWORD=arborist_pass
      - PGHOST=postgres
      - PGPORT=5432
      - PGSSLMODE=disable
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health"]
      interval: 60s
      timeout: 5s
      retries: 10
    depends_on:
      - postgres
  metadata-service:
    image: "quay.io/cdis/metadata-service:2021.03"
    # image: "mds:test"
    container_name: metadata-service
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=metadata_user
      - DB_PASSWORD=metadata_pass
      - DB_DATABASE=metadata
      - DB_PORT=5432
    command: >
      sh -c "/env/bin/alembic upgrade head && /env/bin/uvicorn --host 0.0.0.0 --port 80 mds.asgi:app --reload"
    networks:
      - devnet
  portal-service:
    image: "quay.io/pcdc/gearbox-nginx:master_2021-09-13T16_59_19-05_00"
    container_name: portal-service
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    # command: ["sh", "/dockerStart.sh"]
    # ports:
    #   - "80:80"
      # - "443:443"
    networks: 
      - devnet
    # volumes:
    #   - ./scripts/waitForContainers.sh:/waitForContainers.sh 
      # - ./data/nginx:/etc/nginx/conf.d
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost"]
    #   interval: 60s
    #   timeout: 5s
    #   retries: 10
    depends_on:
      - postgres

  # portal-service:
    # image: "quay.io/cdis/data-portal:2021.03"
    # container_name: portal-service
    # command: ["bash", "/var/www/data-portal/waitForContainers.sh"]
    # networks:
    #   - devnet
    # volumes:
    #   - ./scripts/waitForContainers.sh:/var/www/data-portal/waitForContainers.sh
    #   - ./Secrets/gitops.json:/data-portal/data/config/gitops.json
    #   - ./Secrets/gitops-logo.png:/data-portal/custom/logo/gitops-logo.png
    #   - ./Secrets/gitops.png:/data-portal/custom/createdby/gitops.png
    # environment:
    #   - NODE_ENV=dev
    #   #- MOCK_STORE=true
    #   - APP=gitops
    #   - GDC_SUBPATH=http://revproxy-service/api/v0/submission/
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost"]
    #   interval: 60s
    #   timeout: 5s
    #   retries: 10
    # depends_on:
    #   - postgres
    #   - peregrine-service
    #   - sheepdog-service
  revproxy-service:
    image: "quay.io/cdis/nginx:2021.08"
    container_name: revproxy-service
    networks:
      - devnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./Secrets/TLS/service.crt:/etc/nginx/ssl/nginx.crt
      - ./Secrets/TLS/service.key:/etc/nginx/ssl/nginx.key
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/_status"]
      interval: 60s
      timeout: 5s
      retries: 3
    depends_on:
      - arborist-service
      - fence-service
      - portal-service
      - metadata-service

networks:
  devnet:
volumes:
  psqldata_gear:
  esdata_gear:
